---
# tasks file for sa-jupyterhub

  - include: tasks_python.yml
    when: option_install_python2

  - include: tasks_git.yml
    when: option_install_git

  - include_tasks: tasks_py_anaconda.yml
    when: jupyterhub_python == "anaconda"

  - include_tasks: tasks_python3.yml
    when: jupyterhub_python == "python3"

  - include_tasks: tasks_jupyterhub.yml
