---
# tasks file for sa-jupyterhub
  - name: Set installation facts for python3
    set_fact:
      jupyterhub_python_base_dir: /usr/local
      jupyterhub_python_interpreter: /usr/local/bin/python3
      jupyterhub_pip: /usr/local/bin/pip3
    when: jupyterhub_python == "python3"

  - name: Set installation facts for anaconda
    set_fact:
      jupyterhub_python_base_dir: "{{ anaconda_current_dir }}"
      jupyterhub_python_interpreter: "{{ anaconda_current_dir }}/bin/python"
      jupyterhub_pip: "{{ anaconda_current_dir }}/bin/pip"
    when: jupyterhub_python == "anaconda"

  - name: JupyterHub | create jupyter group
    group: name=jupyter state=present
    become: yes
    tags:
      - jupyterhub

  - name: JupyterHub | create jupyter user
    user: name=jupyter state=present groups=jupyter,shadow
    become: yes
    tags:
      - jupyterhub

  - include: tasks_python.yml
    when: option_install_python2

  - include: tasks_git.yml
    when: option_install_git

  - include_tasks: tasks_python3.yml
    when: option_install_python3

  - include_tasks: tasks_py_anaconda.yml
    when: option_install_anaconda

  - include: tasks_nodejs.yml
    when: option_install_nodejs

  - include_tasks: tasks_jupyterhub.yml
